export const routes = {
  signUp: '/auth/signup',
  signIp: '/auth/signin',
  setup: '/auth/setup',
  dashBaord: '/dashboard/post',
  createPost: '/dashboard/createPost',
  setting: '/dashboard/setting',
  stats: '/dashboard/stats',
  error404: '/404',
  landingPage: '/primate',
  redirect: '/auth/redirect',
  editPost: '/dashboard/editPost',
  postPreview: '/',
  connect: '/connect',
};
