/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_content_delivery_bucket": "primate-dev",
    "aws_content_delivery_bucket_region": "ap-south-1",
    "aws_content_delivery_url": "https://d320m25mt8uqti.cloudfront.net",
    "aws_cognito_identity_pool_id": "ap-south-1:50081512-4086-401e-806b-21f343efb69b",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_Vo6RLgBHq",
    "aws_user_pools_web_client_id": "537af4stk41f0cd5q0kbj73fi4",
    "oauth": {}
};


export default awsmobile;
